language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Lab3_Stack_and_Queue
  - make -j
  - ls
  - ./test/test_Steck
notifications:
  email: false